config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'friends/top'

  get 'home/how'
  
  resources :users, only: %i[index new create edit show update destroy]
  resources :boards, only: %i[index new create edit show update destroy] do
    resources :comments, only: %i[create destroy], shallow: true
  end 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "id", "title", "updated_at", "user_id"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :boards, dependent: :destroy
  has_many :comments, dependent: :destroy
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "crypted_password", "email", "id", "introduction", "name", "player_uid", "salt", "updated_at", "world_rank"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["boards"]
  end

  def own?(object)
    id == object.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @search = Board.ransack(params[:q])
    @boards = @search.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page]).per(20)
  end

  # GET /boards/1 or /boards/1.json
  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user) #, order(created_at: :desc)
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
    @board = current_user.boards.find(params[:id])
  end

  # POST /boards or /boards.json
  def create
    @board = current_user.boards.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to board_url(@board), notice: "募集「#{@board.title}」を作成しました。" }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to board_url(@board), notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url, notice: "募集を削除しました！！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.require(:board).permit(:title, :body, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to board_path(@comment.board), notice: "コメントを作成しました。"
    else
      flash.now[:notice] = ("コメント作成に失敗しました。")
      redirect_to board_path(@comment.board)
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    redirect_to board_path(@comment.board), notice: "コメントを削除しました。"
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(board_id: params[:board_id])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def top
    @search = User.ransack(params[:q])
    @users = @search.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
    @users = User.all
    @users = @users.page(params[:page])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @users = User.all.order("updated_at DESC").limit(2)
  end

  def how
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to(user_path(@user), notice: 'ログインに成功しました')
    else
      flash[:notice] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'ログアウトしました。')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @search = User.ransack(params[:q])
    @users = @search.result(distinct: true).order(created_at: :desc).page(params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      flash.now[:danger] = ("ユーザー作成に失敗しました")
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_back_or_to user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :player_uid, :world_rank, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_form.html.slim
= form_with(model: board) do |form|
  - if board.errors.any?
    #error_explanation

    h2
      = pluralize(board.errors.count, "error")
      |  prohibited this board from being saved:
    ul
      - board.errors.each do |error|
        li
          = error.full_message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .actions
    = form.submit

app/views/boards/edit.html.slim
h1 募集内容編集

.nav.justify-content-end
  = link_to '一覧', boards_path, class: 'nav-link'

= form_with model: @board, local: true do |f|
  .form-group
    = f.label :title, '募集タイトル'
    = f.text_field :title, class: 'form-control', id: 'board_title'
  .form-group
    = f.label :body, '募集内容'
    = f.text_area :body, class: 'form-control', id: 'board_body'
  = f.submit '更新する', class: 'btn btn-primary'

app/views/boards/index.html.slim
.board-index
  h1
    | マルチ募集

= search_form_for @search do |f|
  .input-group.mb-3
    = f.search_field :title_or_body_cont, class: "form-control", placeholder: "検索ワード"
  .input-group-append
    = f.submit "検索", class: "btn btn-outline-primary"

.board-list
  h2
    | 募集一覧

= link_to '新規登録', new_board_path, class: 'btn btn-outline-primary'

= paginate @boards, theme: 'bootstrap-5'

.mb-3
ul.boards
  
  - @boards.each do |board|
    .friend-board
      .card style=("width: 18rem;")
        .card-body.shadow
          .card-columns
            flex-direction:row
              tr
                .user-name
                    = board.user.name
                .board-title
                  td = board.title 
                .board-body
                  td = board.body
                .board-created
                  td = board.created_at.strftime("%Y-%m-%d %H:%M")
                td
                  = link_to '詳細', board_path(board), class: 'btn btn-outline-info'
                td
                  .board-editbutton
                    - if current_user.own?(board)
                      = link_to '編集', edit_board_path(board), class: 'btn btn-outline-info'
                td
                  .board-deletebutton
                    - if current_user.own?(board)
                      = button_to '削除', board, method: :delete, data: { confirm: "募集を削除します。よろしいですか？"}, class: "btn btn-outline-danger"
= paginate @boards, theme: 'bootstrap-5'

app/views/boards/new.html.slim
h1
  | マルチ募集登録

.nav.justify-content-end
  = link_to '一覧', boards_path, class: 'btn btn-primary'

= form_with model: @board, url: boards_path, local: true do |f|
  .form-group
    = f.label :title, 'タイトル'
    = f.text_field :title, class: 'form-control', id: 'board_title'
  .form-group
    = f.label :body, '内容'
    = f.text_area :body, rows: 5, class: 'form-control', id: 'board_body'
  .board-newbutton
    = f.submit '投稿する', class: 'btn btn-primary'

app/views/boards/show.html.slim
.board_show
  h1 募集の詳細

.nav.justify-content-end
  = link_to '一覧', boards_path, class: 'nav-link'
table.table.table-hover.shadow-sm
  tbody
    tr
      th= '投稿者'
      td= @board.user.name
    tr
      th= '募集番号'
      Board.human_attribute_name(:id)
      td= @board.id
    tr
      th= '募集タイトル'
      Board.human_attribute_name(:title)
      td= @board.title
    tr
      th= '募集内容'
      Board.human_attribute_name(:body)
      td= simple_format(h(@board.body), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= '登録日'
      Board.human_attribute_name(:created_at)
      td= @board.created_at.strftime("%Y-%m-%d %H:%M")
    tr
      th= '更新日'
      Board.human_attribute_name(:update_at)
      td= @board.updated_at.strftime("%Y-%m-%d %H:%M")

== render 'comments/form', { board: @board, comment: @comment }

== render 'comments/comments', { comments: @comments }

app/views/comments/_comment.html.slim
| <tr id="comment-
= comment.id
| " class="shadow"> 
td[style="width: 60px"]
  = image_tag 'sample.jpg', class: 'rounded-circle', size: '50x50'
td
  h3.small 
  - #= comment.user.decorate.full_name %
  div id=("js-comment-<%= comment.id %>") 
    = simple_format(comment.body) 
  div id=("js-textarea-comment-box-<%= comment.id %>") style=("display: none;") 
    textarea.form-control.mb-1 id=("js-textarea-comment-<%= comment.id %>")  <%= comment.body %
    button.btn.btn-light.js-button-edit-comment-cancel data-comment-id=("<%= comment.id %>")  キャンセル
    button.btn.btn-success.js-button-comment-update data-comment-id=("<%= comment.id %>")  更新

- if current_user.own?(comment)
  td.action

    ul.list-inline.justify-content-center[style="float: right;"]

      li.list-inline-item
        = button_to comment_path(comment), method: :delete, data: { confirm: "コメントを削除します。よろしいですか？"}, class: "btn btn-danger"
          = icon 'fa', 'trash'
  
- else
  td.action

app/views/comments/_comments.html.slim
.row
  .col-lg-8.offset-lg-2
    table#js-table-comment.table
      = render comments

app/views/comments/_form.html.slim
.row.mb-3
  .col-lg-8.offset-lg-2
    = form_with model: comment, url: [board, comment], local: false, id: 'new_comment' do |f|
      - #= render 'shared/error_messages', object: f.object
      = f.label :"コメント"
      = f.text_area :body, class: 'form-control mb-3', id: 'js-new-comment-body', row: 4, placeholder: Comment.human_attribute_name(:"コメント")
      = f.submit '投稿する', class: 'btn btn-primary'

app/views/friends/top.html.slim
.user-index-title
  h1
    | 旅人一覧

= search_form_for @search do |f|
  .input-group.mb-3
    = f.search_field :name_or_introduction_cont, class: "form-control", placeholder: "ユーザー名"
  .input-group-append
    = f.submit "検索", class: "btn btn-outline-primary"


ul.users
  - @users.each do |user|
    .user-board
      .card style=("width: 18rem;")
        .card-body.shadow
          .column.flex-direction:row
            /# = gravatar_for user, size: 50
            .username-button
              = link_to user.name, user, class: "btn btn-outline-primary"
            br
              = user.name
            br
              = user.world_rank
            br
              = user.introduction
            = link_to user, class: "btn btn-outline-primary"
              = icon 'fa', 'user', 'ユーザーページ'
    = paginate @users, theme: 'bootstrap-5'

app/views/home/home.js.erb
$(function() {
  $('#js-copybtn').on('click', function(){
    // コピーする文章の取得
    let text = $('#js-copytext').text();
    // テキストエリアの作成
    let $textarea = $('<textarea></textarea>');
    // テキストエリアに文章を挿入
    $textarea.text(text);
    //　テキストエリアを挿入
    $(this).append($textarea);
    //　テキストエリアを選択
    $textarea.select();
    // コピー
    document.execCommand('copy');
    // テキストエリアの削除
    $textarea.remove();
    // アラート文の表示
    $('#js-copyalert').show().delay(2000).fadeOut(400);
  });
});

app/views/home/how.html.slim
.how-wrapper
  h1
    | 旅人フレンズとは？？
  p
    | ゲーム原神のフレンドを募集サイトです！
  p
    | このサイトの使い方は↓の通りです！！
  h2
    | 1-新規登録
  p
    | 新規登録しよう！！
  .how-image
    = image_tag('how1 2023-01-16 21.46.20.png', width: "600", height: "300")
  p
    | ↑ヘッダー部分の新規登録ボタンをクリック！
  p
    | 新規登録後、ログインしてマイページを編集しよう!!
  .how-image
    = image_tag('how2 2023-01-16 21.46.58.png', width: "600", height: "300")
  p
    | ↑新規登録画面で名前、メールアドレス、パスワードを決めよう！
  .how-image
    = image_tag('how3 2023-01-16 21.48.03.png', width: "600", height: "300")
  p
    | ↑さっき登録したメールアドレスとパスワードを入力してログインしよう！
  h2
    | 2-マイページ編集
  .how-image
    = image_tag('how4 2023-01-16 21.48.43.png', width: "600", height: "300")
  p
    | ↑ログインした後、マイページ更新へのボタンから編集しよう！
  .how-image
    = image_tag('how5 2023-01-16 21.49.03.png', width: "600", height: "300")
  p
    | ↑マイページで項目ごとに内容を入力しよう！
  h2
    | 3-掲示板投稿、確認
  p
    | 掲示板を使ってマルチプレイの募集をしよう！！
  .how-image
    = image_tag('how6 2023-01-16 21.49.32.png', width: "600", height: "300")
  p
    | ↑各募集から募集内容を確認しよう！
  h2
    | 4-ユーザーページからUIDを確認しアプリから申請
  p 
    | 気になったフレンドとコンタクトを取ろう！！
  p  
    | マイページからUIDをコピーしてゲーム本編からフレンド申請しよう！！
  .how-image
    = image_tag('how7 2023-01-16 21.49.55.png', width: "600", height: "300")
  .how-image
    = image_tag('how8 2023-01-16 21.50.13.png', width: "600", height: "300")
  p
    | ↑ユーザーページへのボランから他のユーザーのマイページに進みをフレンド申請しよう！

app/views/home/top.html.slim
.top-center-text
  h1
    | ゲーム原神のフレンド募集サイト

.top-wrapper
  .top-inner-text
    - image_tag '2021021911190187195.png'
    h2
      | 旅人フレンズ
    p
      | 原神プレイヤーマッチング

.new-loginmenber
  - if logged_in?
    h2
      | ログイン中
  - else
    h2
      | 会員登録はこちらから
      | ↓
    .button-newuser
      = link_to '新規会員登録', new_user_path, class: 'btn btn-outline-primary'

.new-player
  h1
    | 新規登録旅人フレンド
.new-board
  ul.users
    - @users.each do |user|
      .card style=("width: 18rem;")
        .card-body
          .column.flex-direction:row
            /# = gravatar_for user, size: 50
            br
              = user.name
            br
              = user.world_rank
            = link_to user, class: "btn btn-outline-primary rounded-pill"
              = icon 'fa', 'user', 'ユーザーページ'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | GenshinTabibitofriends
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = render 'shared/header'
      = yield
      = render 'shared/footer'

app/views/shared/_footer.html.slim
footer#footer.footer-bottom
  div.footer-container
    div.footer-button-container
      = link_to '#', class: 'btn btn-outline-primary'
        = icon 'fa', 'envelope', 'お問い合わせ'
    div.footer-button-container
      = link_to '#', class: 'btn btn-outline-primary'
        = icon 'fa', 'user-secret', 'プライバシーポリシー'
    div.footer-button-container
      = link_to '#', class: 'btn btn-outline-primary'
        = icon 'fa', 'gear', '利用規約'

app/views/shared/_header.html.slim
.header-container
  header#header.header-top.shadow.bg-body
    .link-button-home
      = link_to root_path, class: 'btn btn-outline-secondary rounded-pill', data: {"turbolinks" => false}
        = icon 'fa', 'home', 'ホーム'
    .link-button-help
      = link_to home_how_path, class: 'btn btn-outline-primary rounded-pill'
        = icon 'fa', 'question', '使い方'
      - if logged_in?
        .link-button
          = link_to user_path(current_user.id), class: 'btn btn-outline-primary rounded-pill', data: {"turbolinks" => false}
            = icon 'fa', 'user', 'マイページ'
        .link-button-user
          = link_to friends_top_path, class: 'btn btn-outline-primary rounded-pill'
            = icon 'fa', 'user-plus', '旅人一覧'
        .link-button
          = link_to  boards_path, class: 'btn btn-outline-primary rounded-pill'
            = icon 'fa', 'chalkboard', '募集一覧'
        .logout-button
          = button_to logout_path, method: :delete, class: 'btn btn-outline-primary rounded-pill', data: {comfirm: "Are you sure?"}
            = icon 'fa', 'power-off', 'ログアウト'
      - else
        .link-button-newuser
          = link_to '新規登録', new_user_path, class: 'btn btn-outline-primary rounded-pill'
        .link-button
          = link_to login_path, class: 'btn btn-outline-primary rounded-pill'
            = icon 'fa', 'power-off', 'ログイン'

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
h1 ログインページ

= form_with url: login_path, local: true do |f|
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .login-button
    = f.submit 'ログイン', class: 'btn btn-primary'

app/views/users/cerate.html.slim
h1 Users#cerate
p Find me in app/views/users/cerate.html.slim

app/views/users/destroy.html.slim
h1 Users#destroy
p Find me in app/views/users/destroy.html.slim

app/views/users/edit.html.slim
.mypage-edit
  h1
    |  マイページ入力画面
  
= form_with model: @user, url: user_path, local: true do |f|
  .form-group
    = f.label :name, 'ユーザーネーム'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :player_uid, 'UID'
    = f.text_field :player_uid, class: 'form-control'
  .form-group
    = f.label :world_rank, '世界ランク'
    = f.text_field :world_rank, class: 'form-control'
  / .form-group
    / = f.label :player, '使用キャラ'
    / = f.text_field :player, class: 'form-control'
  .form-group
    = f.label :introduction, '普段のゲームプレイ内容'
    = f.text_area :introduction, class: 'form-control', size: '20x10'
  .user-editbutton
    = f.submit '作成する', class: 'btn btn-primary'

app/views/users/index.html.slim
.user-index-title
  h1
    | 旅人一覧

= search_form_for @search do |f|
  .input-group.mb-3
    = f.search_field :name_or_introduction_cont, class: "form-control", placeholder: "ユーザー名"
  .input-group-append
    = f.submit "検索", class: "btn btn-primary"


ul.users
  - @users.each do |user|
    .user-board
      .card style=("width: 18rem;")
        .card-body
          .column.flex-direction:row
            /# = gravatar_for user, size: 50
            .username-button
              = link_to user.name, user, class: "btn btn-primary"
            br
              = user.name
            /# br
              /# = user.player_uid
            br
              = user.world_rank
            = link_to "ユーザーページへ", user, class: "btn btn-primary"
    = paginate @users, theme: 'bootstrap-5'

app/views/users/new.html.slim
h1 新規登録

= form_with model: @user, url: users_path, local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .newuser-button
    = button_tag type: 'submit', class: 'btn btn-primary' do
      = icon 'fa', 'pen', '登録'

app/views/users/show.html.slim
- if logged_in? && @user == current_user
  .my-page
    .mypage-image
      h1.font-weight-normal.mt-5.mb-5
        .center-text
          h1
            | マイページ
- else
  .my-page
    .mypage-image
      h1.font-weight-normal.mt-5.mb-5
          .center-text
            h1
              | #{ @user.name }さんのページ
- if logged_in? && @user == current_user
  table.table.table.shadow-sm
    tbody
      tr
        th
          = "名前"
        td
          = @user.name
      tr
        th
          = "ユーザーID"
        td
            p#js-copyid = @user.player_uid 
            = button_tag 'UIDのコピー', type: 'button', id: 'js-copybtn'
            /# p#js-copyalert. copy_alert, "コピーできました！"
      tr
        th
          = "世界ランク"
        td
          = @user.world_rank
      tr
        th
          = "プレイ内容"
        td
          = @user.introduction

  = link_to edit_user_path, class: 'btn btn-outline-primary'
    = icon 'fa', 'wrench', 'マイページ更新へ'
- else
  current_user
  table.table.table
    tbody
      tr
        th
          = "名前"
        td
          = @user.name
      tr
        th
          = "ユーザーID"
        td
          .copy-btn
            p#js-copyid = @user.player_uid 
            = button_tag 'UIDのコピー', type: 'button', id: 'js-copybtn'
            /# p#js-copyalert. copy_alert, "コピーできました！"
      tr
        th
          = "世界ランク"
        td
          = @user.world_rank
      tr
        th
          = "プレイ内容"
        td
          = @user.introduction

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim